#!/bin/sh

# ------------------------------------------------------------------------------
# Convenience build script for the MatMul matrix multiplicaton program.
#
# Copyright (c) 2015 by its authors.
#
# This code is distributed under the BSD3 license. See AUTHORS, LICENSE.
# ------------------------------------------------------------------------------

TARGET='./build/matmul'

USAGE='
NAME
    run - convenience build script for the MatMul program.

SYNOPSIS
    ./run [OPTION] <A nrows> <A ncols> <B nrows> <B ncols>

DESCRIPTION
    Runs the MatMul matrix multiplication program, optionally in debug mode,
    with the given matrix dimensions.

OPTIONS
    -h      Print this help message.

    -d      Run in debug mode, printing the elements of the input and resultant
            matrices.'

print_exit() {
  echo "$1"
  echo "$USAGE"
  exit 1
}

run_with() {
  make clean && make && $TARGET $@
}

debug_with() {
  make clean && make CPPFLAGS="-DDEBUG" && $TARGET $@
}

check_dimens() {
  for dimen in "$@"; do
    case $dimen in
      ''|*[!0-9]*)
        print_exit "Invalid matrix dimension: $dimen"
        ;;
      *)
        ;;
    esac
  done
}

check_flag() {
  if [ "$1" != "-d" ]; then
    print_exit "Invalid flag: $1"
  fi
}

case $# in
  1)
    if [ "$1" = "-h" ]; then
      echo "$USAGE"
      exit 0
    fi
    check_dimens $1
    run_with     $1 $1 $1 $1
    ;;
  2)
    check_flag   $1
    shift
    check_dimens $1
    debug_with   $1 $1 $1 $1
    ;;
  4)
    check_dimens $@
    run_with     $@
    ;;
  5)
    check_flag   $1
    shift
    check_dimens $@
    debug_with   $@
    ;;
  *)
    print_exit "Invalid number of arguments"
    ;;
esac
