#!/bin/sh

print_usage() {
    echo "Usage:  ./run [-d] <A rows> <A cols> <B rows> <B cols>"
    echo ""
    echo "Runs matMul, optionally in debug mode, with the given matrix dimensions"
    echo ""
    echo "Option: -d  Run in debug mode."
}

run_with() {
    make clean && make && ./matMul $1 $2 $3 $4
}

debug_with() {
    if [ "$1" = "-d" ]; then
        make clean && make FLAG="-DDEBUG" && ./matMul $2 $3 $4 $5
    else
        print_usage
        exit 1
    fi
}

case $# in
    1)
        run_with   $1 $1 $1 $1
        ;;
    2)
        debug_with $1 $2 $2 $2 $2
        ;;
    4)
        run_with   $1 $2 $3 $4
        ;;
    5)
        debug_with $1 $2 $3 $4 $5
        ;;
    *)
        print_usage
        exit 1
        ;;
esac
